! This Properties File for Bank Class
!====================================

Account_holderName=Yuvraj
Account_number=458963217845
Current_balance=17000.57
Withdraw_amount=5000.00
Deposit_amount=8000.00