# This Properties File for Student Class
#========================================

Employee_name=David Miller
Employee_id=EMP101
Employee_experience=6
Employee_projectCompleted=false
Employee_basicSalary=75000.00
