# This Properties File for Student Class
#========================================

Student_name=Michael Anderson
Student_id=STU102
Student_percentage=78.50
Student_fee=48000.00
Student_isEligible=false